#!/usr/bin/env python
import argparse
import subprocess
import os

def run_commands(source_file, output_file, lexac_args, output_ll):
    src_path = os.path.abspath(source_file)

    if source_file.endswith(".c"):
        c_file = src_path
    else:
        subprocess.run(["dune", "clean"], check=True)

        base_name = os.path.basename(src_path)
        c_file = os.path.dirname(src_path) + "/" + os.path.splitext(base_name)[0] + ".c"

        dune_command = ["dune", "exec", "lexac", "--", src_path, "-o", c_file]
        if lexac_args:
            dune_command += lexac_args.split()
        subprocess.run(dune_command, check=True)

    passes = [
        "addNoCapture/AddNoCaptureToAsmPass.so", 
        "markInvariant/MarkInvariantPass.so",
        "generateStackMap/GenerateStackMapPass.so"
        ]
    
    include_paths = ["-I", os.path.dirname(os.path.realpath(__file__)) + "/src/stacktrek", "-I", os.path.dirname(src_path), "-I", os.path.dirname(os.path.realpath(__file__)) + "/src/stackwalk"]

    if output_ll:
        clang_ll_command = ["clang", "-S", "-emit-llvm", "-O3", c_file, "-o", source_file.split(".")[0] + ".ll", "-DNO_OFFSET"] + include_paths
        for path in passes:
            clang_ll_command += ["-Xclang", "-fpass-plugin=" + os.path.dirname(os.path.realpath(__file__)) + "/passes/" + path]
        subprocess.run(clang_ll_command, check=True)

    compilation_unit = [c_file, os.path.dirname(os.path.realpath(__file__)) + "/src/stackwalk/stackwalk.c"]
    clang_command = ["clang", "-g", "-O3", "-o", output_file, "-lm", "-lgc", "-Wl,--section-start=.init=0x2000"] + compilation_unit + include_paths # -Wl,--section-start=.init=0x2000 is to make sure the code has a fixed address. This is not necessary when offset_functions.h is created automatically.
    for path in passes:
        clang_command += ["-Xclang", "-fpass-plugin=" + os.path.dirname(os.path.realpath(__file__)) + "/passes/" + path]

    # link-time optimization may seem like a good idea
    # but we disable it because we need to keep the function address stable
    # while changing the definition of stackwalk function
    lto = False
    if lto:
        clang_command += ["-fuse-ld=lld", "-flto"]

    # We compile twice. The first time we produce the binary for analysis.
    subprocess.run(clang_command + ["-DNO_OFFSET"], check=True)
    analyze_command = [os.path.dirname(os.path.realpath(__file__)) + "/src/stackwalk/analyze_binary.py", output_file]
    subprocess.run(analyze_command, check=True)

    # TODO: create offset_functions.h

    # The second time we produce the binary for execution
    subprocess.run(clang_command, check=True)
    # print(" ".join(clang_command))

def main():
    parser = argparse.ArgumentParser(description="Compile lexa programs.")
    parser.add_argument("source_file", type=str, help="The source file to compile")
    parser.add_argument("--output-ll", action="store_true", help="Output the generated LLVM IR")
    parser.add_argument("-o", "--output", type=str, default="a.out", help="The binary output file")
    parser.add_argument("--lexac-args", type=str, default="", help="Arguments to pass to lexac")
    
    args = parser.parse_args()

    run_commands(args.source_file, args.output, args.lexac_args, args.output_ll)

if __name__ == "__main__":
    main()
